maxonrow/maxonrow-go

go.mod, go.sum, x/auth/handler.go, x/auth/msgs.go
txID is created with counter in multisig.
=> use counter for defining txID in multisig.

cmd/mxwd/gentx.go, cmd/mxwd/init.go
=> gentx keyring updated

x/token/fungible/client/cli/query.go, x/token/fungible/client/cli/tx.go, x/token/fungible/client/module_client.go, x/token/fungible/codec.go, x/token/fungible/genesis.go, x/token/fungible/handler.go, x/token/fungible/keeper.go, x/token/fungible/keeper_impl.go, x/token/fungible/keeper_test.go, x/token/fungible/keys.go, x/token/fungible/msgs.go, x/token/fungible/querier.go, x/token/fungible/validate_signature.go, x/token/fungible/validation.go, x/token/nonfungible/client/cli/query.go, x/token/nonfungible/client/cli/tx.go, x/token/nonfungible/client/module_client.go, x/token/nonfungible/codec.go, x/token/nonfungible/handler.go, x/token/nonfungible/keeper.go, x/token/nonfungible/keeper_impl.go, x/token/nonfungible/keeper_test.go, x/token/nonfungible/keys.go, x/token/nonfungible/msgs.go, x/token/nonfungible/querier.go, x/token/nonfungible/validate_signature.go, x/token/nonfungible/validation.go
add in fungible token and non fungible token.
=> add in token.

Makefile, go.mod, go.sum, tests/multisigAcc_test.go, x/auth/msgs.go
Goh request for merging on this
=> multisig test module - Issue on Create multisig tx

go.mod, go.sum, tests/multisig_test.go, x/auth/codec.go, x/auth/handler.go, x/auth/msgs_test.go
=> fix multisig test case

app/ante.go, app/utils.go, tests/multisig_test.go, x/auth/codec.go
multisig test module - Cases happened on while come to process of Sign multisig tx
=> multisig test module - Cases happened on Sign multisig tx

app/app.go, app/maintenance.go, app/validation.go, tests/nonFungible_test.go, tests/tx_test.go, x/auth/handler.go, x/token/nonfungible/handler.go, x/token/nonfungible/keeper.go, x/token/nonfungible/keeper_impl.go, x/token/nonfungible/keys.go, x/token/nonfungible/msgs.go
NFT module:
1. added transfer limit for item.
2. added mint limit.
3. added endorser list in nft.
Multisig module:
1. remove delete pending tx event.
=> Enable nft module, small fixes at multisig module.

x/token/nonfungible/querier.go
Added endpoint for mxw-sdk-js to query nft item data.
=> Added end point for query NFT item data

x/token/nonfungible/keeper_impl.go
implemented, if public, user can only mint to themselves.
=> if it is public, user only can mint to themselves for nft item.

tests/non_fungible_test.go, x/token/nonfungible/codec.go, x/token/nonfungible/handler.go, x/token/nonfungible/keeper.go, x/token/nonfungible/keeper_impl.go, x/token/nonfungible/msgs.go
1. added properties into nft.
2. change metadata into string array for nft.
3. Upon creation properties and metadata setted for nft.
4. token owner able to update metadata.
=> added properties and changed metadata into string array for nft.

app/ante.go, app/app.go, types/resutl_log.go, x/auth/handler.go, x/bank/handler.go, x/kyc/handler.go, x/kyc/keeper.go, x/maintenance/handler.go, x/nameservice/keeper.go, x/token/fungible/keeper.go, x/token/fungible/keeper_impl.go, x/token/nonfungible/keeper.go, x/token/nonfungible/keeper_impl.go
1. resultLog restructured.
2. events revamped.
3. multisig developed(need more discussion before launch)
=> multisig module develop, modify resultLog implementation.

.gitignore, go.sum, tests/cli_test.go
=> cli test send fixed

app/app.go, app/rpc.go, x/token/nonfungible/keeper.go
Add new rpc method for listing non-fungible token list
=> Add new rpc method for list of non-fungible tokens

app/rpc.go, x/fee/keeper.go
* Added methods in keeper
* Update the RPC fee info
=> Keeper and fee info updated

app/validation.go, tests/multisig_test.go, x/auth/handler.go
1. delete transaction only owner of the multisig account allow to delete pending transaction.
=> all checking move to check tx layer for multisig.

app/validation.go
@githubckgoh1439 there is error in test case kindly check for your test case. 
@b00f i added few validation.
=> check group account is it exist, validate internal transaction message.

CHANGELOG.md, app/app.go, app/rpc.go, tests/tx_test.go
- disable multisig module
- committed query account fix for issue #103
=> final check on production grade version.

EVENTS.md, x/token/fungible/keeper.go
- fix ft approve event
- updated event.md
=> fix ft approve event, updated event.md

x/maintenance/keeper.go, x/token/fungible/keeper.go, x/token/fungible/keeper_impl.go
update system wallet address to mxw1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqgcpfl3
=> chg system wallet address to mxw1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqgcpfl3

x/token/fungible/validation.go, x/token/nonfungible/validation.go
=> Remove TODO comments

tests/main_test.go, tests/tx_test.go, utils/process.go
Make sure all fess distributed to the validator.
=> Check distributed fee for test txs

cmd/mxwcli/main.go, x/token/nonfungible/client/cli/query.go, x/token/nonfungible/client/cli/tx.go, x/token/nonfungible/client/module_client.go
* added Nft cli client function
=> added the nft cli client

cmd/mxwd/utils.go, x/token/nonfungible/client/cli/query.go
* Changes made for init-auto command
* nft query command
=> chages made in init-auto command and query command for item

cmd/mxwd/main.go
* few changes made to generate multiple node with gentx
=> update the function to create the multiple node

x/token/nonfungible/msgs.go
=> Enable update endorser list to accept empty.

x/maintenance/client/cli/tx.go
=> fix validator key string in cli

app/app.go, app/rpc.go
Update RPC method to get information about FT/NFT
Fixing #156
=> Update RPC method to get information about FT/NFT

app/validation.go, x/token/nonfungible/msgs.go, x/token/nonfungible/validation.go
=> add in validation for token(nft/ft) upon burning.

x/token/nonfungible/msgs.go, x/token/nonfungible/validation.go
this fix fix the issue #169 and #167
=> set endorserlist limit to 10

CHANGELOG.md, app/validation.go, version/version.go, x/token/nonfungible/msgs.go
updated changelog and version.
=> updated changelog and version.

x/token/fungible/handler.go
- fix spelling error for ft accept transfer token ownership and reject transfer token ownership
=> fix spelling error

CHANGELOG.md
=> fix changelog typepo.

app/validation.go, tests/non_fungible_test.go, x/token/nonfungible/handler.go, x/token/nonfungible/keeper.go, x/token/nonfungible/keeper_impl.go, x/token/nonfungible/msgs.go, x/token/nonfungible/validation.go
NFT -  Implement check endorser list limit during 
1.  Approval process
2.  Update endorser list process
=> nft - check endorserlist limit during approval and update endorser list

app/fee.go, app/validation.go, x/fee/keeper.go
=> added added nft update item metadata into token action.

app/validation.go, x/token/fungible/keeper.go, x/token/fungible/keeper_impl.go, x/token/nonfungible/keeper.go, x/token/nonfungible/keeper_impl.go
Update with meaningful error messages for:
1. validation.go
2. non-fungible token
3. fungible token
=> Update with meaningful error messages

CHANGELOG.md
Update CHANGELOG.md with latest changes info.
=> Update CHANGELOG.md under Version 1.3.6

CHANGELOG.md, app/validation.go, x/token/nonfungible/keeper.go, x/token/nonfungible/keeper_impl.go
We have come to agree that remove the default endorser list limit
- remove default endorser list limit
- updated change log
=> Remove endorser list limit

app/validation.go, x/token/nonfungible/keeper.go, x/token/nonfungible/keeper_impl.go
Update error code for message 'Endorserlist limit exceeded'.
=> Use CodeInternal for message 'Endorserlist limit exceeded'

app/validation.go, types/errors.go, x/token/nonfungible/keeper.go, x/token/nonfungible/keeper_impl.go
Changed in files of:
1. validation
2. NFT - keeper
=> Using error code 'CodeTokenLimitExceededError'

CHANGELOG.md, app/validation.go, docker/Dockerfile.develop, docker/README.md, tests/fungible_test.go, version/version.go
- added docker file for creating image from develop branch
- fix validation upon minting nft to check for is token owner
- update change log
=> Added docker file for building from develop, fix validation upon minting nft to check for is token owner.

x/token/nonfungible/querier.go
Add item owner to item query info
=> Add item owner when user querry an NFT item

x/fee/client/cli/tx.go
- fix nft cli set token action fee setting.
- fix ft cli set token action fee setting.
=> fix nft/ft token action fee setting.

app/app.go, app/rpc.go
* Added the rpc endpoint to get authoriser of Fungible token
* Added the rpc endpoint to get authoriser of NonFungible token
=> Added New RPC Endpoint

x/token/nonfungible/querier.go
- remove key item form iteminfo structure for querry nft item info
=> remove key item from iteminfo structure for querry nft item info.
